
const note = {
    title: "Day 1 - I am great as Fuck",
    content: `Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) 
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        Its the first ever note to Every reader asks questions at a story’s beginning. Some are basic: What is Hogwarts? Who is Dumbledore? Why does Voldemort hate Harry? Whereas others are more specific. In Harry Potter and the Goblet of Fire, readers wonder who at Hogwarts is trying to kill Harry. This important question offers an opportunity to steer readers toward the wrong solution and distract them from the right one. An unanticipated outcome is the definition of a plot twist at its core.
        The goblet of fire chooses Harry to compete in the potentially lethal Triwizard Tournament that is being hosted at his school. This convinces Harry and his friends that his foe is attempting to murder him on behalf of the true monster, the spirit of Voldemort.         
        When Harry becomes one of the tournament winners, he’s transported to a graveyard, where a resurrected Voldemort nearly destroys him. After Harry survives, his enemy, who had been disguised as Professor Moody, reveals himself. Barty Crouch Jr. manipulated the goblet and the tournament so he could use Harry’s blood to revive Lord Voldemort. He put Harry in danger, not to kill him, but to guide him to He Who Must Not Be Named.   
        Incidents that previously seemed unrelated now become deeper. Cedric, Hagrid, and Dobby aided Harry in overcoming the tournament challenges, unknowingly pushing him toward victory and his fight with Voldemort. Readers assumed his friends were being helpful, but their advice originated from Crouch Jr.
        This plot twist addresses the question readers believed was already solved (who are Harry’s allies?) and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR
        and the one yet to be resolved (who is targeting Harry?). It’s memorable because it startles readers, yet they also realize they overlooked the evidence that was staring them in the face. If Rowling hadn’t inserted a bucketful of clues, her reveals would have been less impressive. be DIsplayed on the App The -f is actually required because of the rebase. Whenever you do a rebase you would need to do a force push because the remote branch cannot be fast-forwarded to your commit. You'd always want to make sure that you do a pull before pushing, but if you don't like to force push to master or dev for that matter, you can create a new branch to push to and then merge or make a PR.`,
    date: "3-sep-22",
    tag: "Sad",
};

var notes = [
    note,
    {
        title: "Day 2",
        content:
            "kahgdgakd asohd asdha soduhas oduash doasgd uasgdi asdgas odgaou saudg asohds",
        date: "2-dec-22",
        tag: "code",
    },
    {
        title: "Day 3",
        content:
            "kahgdgakd aasldh oahsd uhas odha doasuhdasuodhas odhasd asohdas oudhas duosahd oasudgh asufgduifgdsiuf daiufgha ofhao dfhaoudf asoudfha sododgaou saudg asohds",
        date: "2-jan-23",
        tag: "friends",
    },
    {
        title: "Day 4 - Got a new Car",
        content: `Sustaining your car is a very important step that every car owner must follow to increase the life of their car and make it look brand new all the time and to maintain your car. Always maintain your car servicing schedule and never overlook or delay it so that your car is always up to the mark with its best performance.

        Precautionary maintenance is the best thing, which you can do for your car to maintain your car to increase its life and also save money on repairs. Never ignore your car engine tips like when to change oil, check tire pressure, get inspection's, etc. The best car engine tips you can get is from your owner's manual. Nevertheless, we have provided some car engine tips to maintain your car as follows:
        
        Check your Air Filter
        Many car problems are due to broken-down air filters attached to them and the wear caused by them. You should get your filters changed every 12 months or after 15000 km, whichever comes fast. Don't ignore this car engine tip if ignored it might lead to problems in your AC and you are breathing unhealthy air in your car. You can get the filter replaced at your mechanic in just 10 minutes.
        
        Inspect Fluids and Tyre Pressure Regularly
        To maintain your car, you shouldn't ignore or delay these components of your car. You should always pay extra attention to your tires and fluids. The task to check it takes about 10 minutes only. All you need to do is open the engine when it's cooled down and detach the oil dipstick. Clean it thoroughly and put it back again. Now when you pull it, you will notice the oil stuck to it. This way you will know when to change the engine oil. While doing this also check your power steering fluid level and also the hoses and belts for any signs of wear. After warming up your car check the transmission fluid level too. Now for your tyres, you can check the pressure by using a gauge and ensure that it has the correct ﻿pressure for all tyres. Conduct this every other week for less wear to your tyre.
        
        Check your Battery
        We all have had our car batteries run out when we need it the most. We all faced the situation where we are left stranded on the road in the middle of the nights with just the lights of our cell phones. To avoid this situation never ignore your low battery sign and always get it checked regularly to maintain your car. Check for leakage or any mineral build up around it. Clean it with a battery cleaning brush and do this whenever necessary.
        
        Change your Spark Plugs
        If you notice that your engine is not working efficiently, then the reason probably is the spark plugs. If not checked if they wear out easily and will be covered in a build-up. Check and get them replaced if needed to maintain your car. They usually last around 40,000 km; see the owner's manual for an accurate idea as it is specifically written for your car and gives better details for car engine tips.
        
        Get your Tyres Rotated and Balanced
        This is the easiest trick to maintain your car to prevent wearing of tyres and make them last longer, and the trick is to get them rotated once in a while. All tyres do not wear at the same time. So, by rotating the front and rear tires, you balance the wear and make them more durable. Ensure that the tyres of your car are always perfectly aligned as non-aligned tyres can make you lose control of your car and cause accidents.
        
        Clean your Windshields and Replace the Wipers
        The dirty windshield can prove to be a lot of hassle if they are not cleaned regularly and can cause accidents too. It is very important for the driver to get the perfect and clear view of the road for safe driving. If you don't clean them the dirt and the dirt get accumulated there and can cause the quality of the glass to deteriorate. So, it’s necessary to maintain your car.
        
        Inspect and Replace Serpentine Belts
        Thoroughly inspect your serpentine belts and check for wears. If these belts fail, they can cause damage to the other accessories to make the bill of your repair too high. It is recommended to get it checked every 60,000 km but you should the owner's manual to get the best car engine tips for your car.
        
        Check your Brakes
        It also ensures a very safe driving for the passengers in the car and also the people around you. Getting your brakes checked and replaced is like changing your car's oil, Simple and easy way to maintain your car.
        
        Ensure the Working of the Cooling System
        The pipes, which carry the engine coolant can damage very quickly as they transport high-pressure fluids, which can break if the pressure is too high. Also, the heater hoses face the same problem as they carry hot coolant to the passenger compartment. To maintain your car, you should regularly check the amount of coolant in the engine.`,
        date: "26 jan",
        tag: "car",
    },
];

function getDate(){
    const D = new Date();
    const option = {
        month: "short",
        day: "numeric",
        year: "numeric"
    };
    const curDate = D.toLocaleDateString("en-IN", option);
    return curDate;
}

function setData(data){
    notes = data;
    console.log(notes);
}

function addNote(){
    const newNote = {
        title: "Note Title...",
        content: "Note Body...",
        date: getDate(),
        tag: "Add Tag..."
    }

    notes.unshift(newNote); //adds at front
    let lastIdx = notes.length-1;
    return notes[lastIdx];
}

function setNote(data, idx){
    notes[idx] = {
        title: data.title,
        content: data.content,
        date: data.date,
        tag: data.tag 
    }
}

export default notes;
export {addNote, setData, setNote, getDate};